### ISSUE TITLE
Using JIRA instead of Waffle?

### ISSUE THREAD

**Issue by michaellorman** [tcm-labs/workflow#19]
@maniananth @nelsonic Here is the list of Waffle issues we have now:
1. Sub-tasks can`t be created under user story. They can be created as separate tickets.
2. Stories can`t be created under epics. 
3. Using labels instead of creating tickets of specific types (bug, story defects, epic, tech task), priority, milestone
4. No special separate entity like backlog. Only column is Waffle can be used as a Backlog.

**Comment by konstantin-ciklum** [comment]
Additions to Michael's comment:
- No possibility to set "required" fields or actions
- Additional step to add attachment to ticket
- No ability to have templates for tickets. Such as Defect which has the same structure all the time
- Inconvenient ticket history tracking. Not clear what and when have been changed.
- No triggering of the notifications to "watchers" regarding some changes in tickets
- Board maintenance becomes harder with its growth
- Waffle filtering doesn't support logical operators AND, OR, IN, NOT IN e.t.c.

**Comment by nelsonic** [comment]
@michaellorman _good_ question, ***thank you*** for opening this issue to discuss it! 👍 

The `main` _reason_ we don't use JIRA in ROAM is because having **_multiple_ systems**
**fragments** the project **communication** and **information/knowledge**.

> In a distributed/remote team communication effectiveness is the _single_ most _critical_ success factor (_or predictor of failure_). If **information** is **stored** in **_multiple_ places** e.g: JIRA _and_ GitHub `.then` people do not know _where_ to look for it; this ends up ***wasting time***.

We use GitHub as our "***Single Source of Truth***".
So that ["_onboarding_"](https://en.wikipedia.org/wiki/Onboarding) a new team member is as smooth as possible because they only have _one_ place to look for _everything_.

Ensuring _All_ project detail is stored in a _single_ place means that ("full text") search _works_ for _finding_ what you are looking for in the project.
e.g: https://github.com/search?q=org%3Atcm-labs+payment
![image](https://user-images.githubusercontent.com/194400/32044990-c9d82caa-ba47-11e7-871e-24a08e539b45.png)
the search results includes Issues (User Stories, Bugs & Technical Tasks) and Code in **_one_ place** which makes finding what you are looking for **_much_ faster** than having to search _multiple_ places. 

Projects that use JIRA _inevitably_ also end up using "Confluence" which means instead of having _one_ place to store information you now have _three_ (JIRA, Confluence and GitHub!_)

> Our _objective_ in defining our Workflow (_and selecting our tools_) 
is to _minimise_ the amount of time it takes for a new member of the team to be delivering _value_.
> The more tools we have to learn (_and then use_) the more time it takes to get work done.
> Most companies/teams do not have an _accurate_ figure for how long it takes to a new team member to become "_productive_".
> You (_@michaellorman_) might be _comfortable_ with JIRA workflow because you have _years_ of experience. So it can be _difficult_ to see JIRA from the perspective of a "_beginner_" ...

> https://twitter.com/iamdevloper/status/910860663651749889
![image](https://user-images.githubusercontent.com/194400/32041650-7ceb249c-ba3d-11e7-9408-ffb7a6e9d49e.png)
JIRA UI is _universally_ regarded as "confusing".
Which is why Atlassian have _recently tried_ to _simplify_ JIRA: https://twitter.com/JIRA/status/911346377665531904

GitHub Project Boards are _simple_ by `default` because there are _fewer_ "_features_".
