### ISSUE TITLE
Simplifying Waffle flow

### ISSUE THREAD

**Issue by michaellorman** [tcm-labs/workflow#20]
Yesterday there was a discussion between devs and QAs how to simplify Waffle flow, make transparency for the team and avoid additional communication before testing:
1. Added Waiting Next Build column. Devs will move tickets here after ticket is Ready for Test, but build is not provided yet. QAs or devs will move tickets from this column to Ready for Test after build is available.
2. Ready for Test column should be used only for tickets, which should be tested by QAs. In case developer want to test smth, he can move ticket to Waiting Next Build column after he finish implementation, and move it to In Test state after build is available.
3. QAs should test only user stories and bugs (story defects). QAs don`t test sub-tasks.

**Comment by nelsonic** [comment]
Simply adding _another column_ to Waffle as a "holding space" for stories/bugs that are waiting for the `next build` does **not _solve_ the problem** of speeding up the time-to-build the React Native App.

> There is _already_ a ***temporary*** label: **`next build`** for this purpose until we _streamline_ the build. The story remains "In Dev" but with the **`next build`** _label_ applied to it.

We need to ***automate*** the React Native App build process so that it can be done when ever there is a new feature to be tested. see: https://github.com/tcm-labs/tcm-payg-app/issues/96

@michaellorman this might help: https://en.wikipedia.org/wiki/5_Whys & https://en.wikipedia.org/wiki/Lean_software_development

**Comment by michaellorman** [comment]
@nelsonic Issue we are trying to resolve by adding new column is to have transparency for QAs that story/story defect is ready, but can`t be tested yet. Don`t see the reason why QAs should check the labels of the tickets instead of checking one column to plan their testing activities.
And I agree that this is just a temporary solution while we don`t have automated build process.
